services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hotels
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  go-bank-backend:
    image: razanakotomandresy/hotels-go
    # build: .
    # ports:
    #   - "8080:8080"
    # depends_on:
    #   - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5433
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: hotels
      JWT_SECRET: secret
      CRYPT_KEY: CRYPT_KEY
      SERVER_PORT: 8080

volumes:
  pgdata:
